/* This file is generated by pcode_autog
** Copyright(c) Laked.Goo, ALL RIGHTS RESERVED.
**
** Purpose: Includes
**
*/
#ifndef _PROTOCOL_INCLUDES_H_
#define _PROTOCOL_INCLUDES_H_


#include "simpleppdef.h"
#include "xxsocket.h"
#include "assert.h"
#include <iomanip>


#endif

